[package]
name = "rust_kirigami_calc"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
cxx-qt = "0.6"
cxx-qt-lib = "0.6"
meval = "0.2"    # Changed from 0.4 to 0.2
regex = "1"      # Added for handling '!'

[build-dependencies]
cxx-qt-build = "0.6"
